### PR TITLE
fix(platform): stub _symmetric_memory when the package cannot be imported

### LINKED ISSUE #509: fix(platform): stub torch.distributed._symmetric_memory for torch < 2.8
Release tracking issue for the `flagos2.2-rc2` release.

Linked PR: https://github.com/flagos-ai/vllm-plugin-FL/pull/491

`vllm.distributed.parallel_state` imports `torch.distributed._symmetric_memory` at module level, but that module only exists in PyTorch 2.8+. Vendor torch builds on 2.7.x — iluvatar corex ships torch 2.7.1 — therefore crash with `ImportError` before the engine core starts, in both the API-server and spawned worker processes.

### PR DESCRIPTION
**Pull request by tengqm**
### PR Category

Core

### PR Type

Bug Fix

### Description

Fix the `torch.distributed._symmetric_memory` stub so it also covers the vendor torch builds it was added for.

### Problem

#491 probes that module by importing it, and stubs it only when the import raises `ModuleNotFoundError` naming the submodule itself. That covers torch builds which do not ship the package (torch 2.7.1+cpu, cambricon 4.4.3), but not the shape iluvatar corex 4.4.0 has:

```
File "/flagos/lib/python3.12/site-packages/torch/distributed/_symmetric_memory/__init__.py", line 16, in <module>
    from torch._C._distributed_c10d import _SymmetricMemory, Work as _Work
ImportError: cannot import name '_SymmetricMemory' from 'torch._C._distributed_c10d' (unknown location)
```

The package is present; its own import fails because `_SymmetricMemory` only exists from torch 2.8. `ImportError` is not caught, so on `0.3.0-rc2` (torch 2.7.1+corex.4.4.0) `import vllm_fl` raises and no engine can start — measured on an app image built from the `v0.3.0-rc2.post2` tag, `vllm_fl/__init__.py` line 32. This is the failure reported in #27.

### Fix

Catch `ImportError` as well, and install the stub in both shapes:

- submodule absent → stub;
- submodule present but unimportable → stub;
- submodule imports fine (torch ≥ 2.8) → untouched, the real module stays;
- `ModuleNotFoundError` naming anything else → still raises, since that is a missing dependency of the real module rather than an older torch.

### Testing

The probe, lifted verbatim from the patched file, was run against a synthetic `torch` package for each shape:

| shape | before | after |
|---|---|---|
| submodule absent | stub | stub |
| present, `_SymmetricMemory` missing | **raises ImportError** | stub |
| present and importable | real module kept | real module kept |
| present, dependency missing | raises | raises |

Not run on iluvatar hardware — a `vllm serve` run on corex 4.4.0 has to confirm it end to end.

This PR was written in part with the assistance of generative AI.

### CODE REVIEW

**Comment by tengqm** [comment]
Verified end to end on the platform the fix is for.

**Setup** — Iluvatar CoreX BI-V150 (ix15), FlagOS runtime `flagos-runtime-iluvatar-corex4.4.0:2.2.0`, python 3.12, torch 2.7.1+corex.4.4.0, flag_gems 5.4.0rc2.post3, FlagTree path (runtime default compiler). A wheel built from this PR's head was pushed to the iluvatar index only and installed over `vllm==0.24.0+flagos`:

```
Successfully installed vllm-plugin-fl-0.3.0rc2.post2+g993dbb7.d20260920
```

**Result** — plugin imports, server comes up, real completion returned:

```
Platform plugin fl is activated
serve ready after ~110s
completion returned (status=200): ' Paris. The capital of Germany is Berlin. The capital of Italy is Rome.'
```

Qwen3-4B, single request, no env workaround. On the pre-fix wheel the same image dies at `vllm_fl/__init__.py` line 32 with the `ImportError` in the description, before the platform plugin is reached.

Filed as #550. Not run: the FlagTree/Triton dual-path comparison (only the runtime default path was exercised, which is what the app image ships), and corex 4.5.0 — no regression expected there, since torch 2.10 ships a working `_symmetric_memory` and the probe leaves the real module in place.

**Comment by tengqm** [comment]
Trimmed the added comment block from 12 lines to 4 (commit 8387086, comment-only). The probe logic is unchanged — re-checked the four shapes (absent / present-but-unimportable / importable / dependency-missing) with the same result as before, so the corex 4.4.0 evidence still stands.

**Review by physics31415926 — APPROVED** [review]
