### PR TITLE
修复 v0.2.0-rc0.post1 与 vLLM 0.20.2 的兼容性问题

### LINKED ISSUE #451: v0.2.0-rc0.post1 与 vLLM 0.20.2 存在多个兼容性问题
# Issue: v0.2.0-rc0.post1 tag incompatible with vLLM 0.20.2 on Ascend 910c

## Summary

The `v0.2.0-rc0.post1` tag claims to support vLLM 0.20.2 (per README), but contains multiple API incompatibilities that prevent it from working with vLLM 0.20.2. Testing on Ascend 910c reveals 6 critical incompatibilities that suggest the codebase was developed against a newer vLLM version and incorrectly tagged for 0.20.2.

## Environment

- **Hardware**: Ascend 910c × 16 (64GB each)
- **CANN**: 9.0.0
- **OS**: openEuler 22.03 LTS-SP4 (ARM64)
- **Docker Image**: `quay.io/ascend/vllm-ascend:v0.20.2rc1-a3`
- **vLLM**: 0.20.2 (empty install: `VLLM_TARGET_DEVICE=empty pip install vllm==0.20.2`)
- **FlagGems**: 5.4.0-rc0 (branch `5.4.0-rc0`)
- **FlagTree**: 0.7.0-rc0-triton3.5 (branch `0.7.0-rc0-triton3.5`)
- **vllm-plugin-FL**: v0.2.0-rc0.post1 (commit `48af29e`)
- **Model**: Qwen3.6-35B-A3B (tensor_parallel_size=2)

## Reproduction Steps

1. Install vLLM 0.20.2 empty:
   ```bash
   VLLM_TARGET_DEVICE=empty pip install vllm==0.20.2 --no-build-isolation
   ```

2. Install FlagGems 5.4.0-rc0:
   ```bash
   git clone https://github.com/FlagOpen/FlagGems.git
   cd FlagGems && git checkout 5.4.0-rc0
   pip install -e .
   ```

3. Install FlagTree with Ascend backend:
   ```bash
   git clone https://github.com/flagos-ai/FlagTree.git
   cd FlagTree && git checkout 0.7.0-rc0-triton3.5
   pip install nanobind>=2.4,<3
   pip install -r python/requirements-ascend.txt
   export PATH=~/.flagtree/ascend/llvm-7d5de303-ubuntu-aarch64-python311-compat/bin/:${PATH}
   export FLAGTREE_BACKEND=ascend
   MAX_JOBS=32 pip install . --no-build-isolation -v
   ```

4. Install vllm-plugin-FL v0.2.0-rc0.post1:
   ```bash
   git clone https://github.com/flagos-ai/vllm-plugin-FL.git
   cd vllm-plugin-FL && git checkout v0.2.0-rc0.post1
   pip install --no-build-isolation -e .
   ```

5. Attempt to start vllm serve:
   ```bash
   export VLLM_PLUGINS=fl
   export VLLM_FL_PLATFORM=ascend
   export ASCEND_RT_VISIBLE_DEVICES=0,1
   vllm serve /models/Qwen3.6-35B-A3B \
     --host 0.0.0.0 --port 7023 \
     --trust-remote-code \
     --max-model-len 512 \
     --enforce-eager \
     --served-model-name qwen \
     --tensor-parallel-size 2 \
     --gpu-memory-utilization 0.8 \
     --no-enable-chunked-prefill \
     --no-async-scheduling \
     --no-enable-prefix-caching
   ```

### Issue 1: DeviceDetector import path changed in FlagGems 5.4.0-rc0

**Error:**
```python
ModuleNotFoundError: No module named 'flag_gems.runtime.backend.device'
```

**Location:** `vllm_fl/utils.py:8`

**Root Cause:** FlagGems 5.4.0-rc0 renamed `device.py` to `device_finder.py`, but plugin still imports from old path.

**Fix:**
```python
# Line 8 in vllm_fl/utils.py
# Before:
from flag_gems.runtime.backend.device import DeviceDetector
# After:
from flag_gems.runtime.backend.device_finder import DeviceDetector
```

---

### Issue 2: SharedFusedMoE does not exist in vLLM 0.20.2

**Error:**
```python
ModuleNotFoundError: No module named 'vllm.model_executor.layers.fused_moe.shared_fused_moe'
```

**Location:** `vllm_fl/dispatch/backends/vendor/ascend/impl/fused_moe/fused_moe.py:37`

**Root Cause:** vLLM 0.20.2 does not have `SharedFusedMoE` class. This was added in later vLLM versions.

**Fix:**
```python
# Line 37 in vllm_fl/dispatch/backends/vendor/ascend/impl/fused_moe/fused_moe.py
# Before:
from vllm.model_executor.layers.fused_moe.shared_fused_moe import SharedFusedMoE

# After:
try:
    from vllm.model_executor.layers.fused_moe.shared_fused_moe import SharedFusedMoE
except ImportError:
    # vLLM 0.20.2 doesn't have SharedFusedMoE
    SharedFusedMoE = None

# Also update class definition around line 408:
# Before:
class AscendSharedFusedMoE(SharedFusedMoE, AscendFusedMoE):

# After:
class AscendSharedFusedMoE(*(([SharedFusedMoE, AscendFusedMoE] if SharedFusedMoE else [AscendFusedMoE]))):
```

---

### Issue 3: MMEncoderAttention does not accept multimodal_config in vLLM 0.20.2

**Error:**
```python
TypeError: MMEncoderAttention.__init__() got an unexpected keyword argument 'multimodal_config'
```

**Location:** `vllm_fl/dispatch/backends/vendor/ascend/impl/mm_encoder_attention.py:48-58`

**Root Cause:** vLLM 0.20.2's `MMEncoderAttention.__init__()` only accepts 5 parameters (`num_heads`, `head_size`, `scale`, `num_kv_heads`, `prefix`), but plugin passes `multimodal_config` to `super().__init__()`.

**Fix:**
```python
# Line 48-58 in vllm_fl/dispatch/backends/vendor/ascend/impl/mm_encoder_attention.py
super().__init__(
    num_heads=num_heads,
    head_size=head_size,
    scale=scale,
    num_kv_heads=num_kv_heads,
    prefix=prefix,
    # multimodal_config=multimodal_config,  # Remove this line for vLLM 0.20.2 compatibility
)
```

---

### Issue 4: ASCEND_FL attention backend not registered in AttentionBackendEnum

**Error:**
```python
ValueError: Unknown attention backend: 'ASCEND_FL'. Valid options are: FLASH_ATTN, FLASH_ATTN_DIFFKV, TRITON_ATTN, ...
```

**Location:** 
- Backend definition: `vllm_fl/dispatch/backends/vendor/ascend/impl/attention.py:436`
- Error occurs during: `vllm.model_executor.layers.attention.attention.py:358`

**Root Cause:** Plugin's `AscendFlashAttention` backend returns name "ASCEND_FL" via `get_name()`, but this backend is never registered in vLLM 0.20.2's `AttentionBackendEnum`. vLLM 0.20.2 uses a strict enum-based backend registry (`vllm.v1.attention.backends.registry.AttentionBackendEnum`) that only accepts pre-registered backend names.

**Analysis:** Plugin needs to either:
1. Register ASCEND_FL using vLLM's `register_backend()` mechanism with `AttentionBackendEnum.CUSTOM`
2. Or modify the backend name to match one of the existing enum members

**Expected Fix:** Plugin should register the backend during initialization, likely in platform registration code:

```python
from vllm.v1.attention.backends.registry import register_backend, AttentionBackendEnum
from vllm_fl.dispatch.backends.vendor.ascend.impl.attention import AscendFlashAttention

# Register ASCEND_FL backend
register_backend(
    AttentionBackendEnum.CUSTOM,
    f"{AscendFlashAttention.__module__}.{AscendFlashAttention.__qualname__}"
)
```

However, I cannot locate where this registration should occur in the current codebase. The plugin needs proper documentation on how Ascend backend registration works with vLLM 0.20.2.

---

### Issue 5: nanobind version conflict
FlagTree requires `nanobind>=2.4` but `<3.0`. If nanobind 3.x is installed, cmake fails with version incompatibility.

### Issue 6: Missing cann-shmem dependency
FlagTree's Ascend backend requires `cann-shmem` package (from `python/requirements-ascend.txt`), but this is not documented in plugin installation instructions.

---

## Root Cause Analysis

The code in `v0.2.0-rc0.post1` appears to have been developed against a **newer version of vLLM** (likely 0.24.0+) and incorrectly tagged for 0.20.2 compatibility:

1. **SharedFusedMoE** was introduced after vLLM 0.20.2
2. **multimodal_config parameter** for MMEncoderAttention was added after 0.20.2
3. **Attention backend registration system** may have changed between versions

Evidence from commit history:
- Commit `1326a33` mentions "upgrade vllm to 0.20.2 on ascend platform"
- But later changes merged code from branches targeting vLLM 0.24.0
- The `v0.2.0-rc0` branch HEAD (`90e8c49`) is from 2024, but contains 2025+ code

---

## Recommendation

**Option 1 (Preferred):** Create a clean vLLM 0.20.2-compatible release:
1. Fork from the last truly 0.20.2-compatible commit (before SharedFusedMoE introduction)
2. Apply only the necessary fixes (DeviceDetector, nanobind, cann-shmem)
3. Tag as `v0.2.0-rc0.post2` or similar
4. Document the attention backend registration mechanism for vLLM 0.20.2

**Option 2:** Update README to clarify that v0.2.0-rc0.post1 actually requires vLLM 0.24.0+, and create a separate tag for true 0.20.2 support.

**Option 3:** Provide a compatibility layer that detects vLLM version and adjusts behavior accordingly.

---

## Expected Outcome

After fixes, the following should work without errors:

```bash
export VLLM_PLUGINS=fl
export VLLM_FL_PLATFORM=ascend
export ASCEND_RT_VISIBLE_DEVICES=0,1

vllm serve /models/Qwen3.6-35B-A3B \
  --host 0.0.0.0 --port 7023 \
  --trust-remote-code \
  --tensor-parallel-size 2 \
  --enforce-eager

# Expected output:
# INFO:     Uvicorn running on http://0.0.0.0:7023 (Press CTRL+C to quit)
# INFO:     Application startup complete.
```

And inference should succeed:
```python
from openai import OpenAI
client = OpenAI(api_key="EMPTY", base_url="http://localhost:7023/v1")
response = client.chat.completions.create(
    model="qwen",
    messages=[{"role": "user", "content": "Hello"}]
)
print(response.choices[0].message.content)
```

---

## Workaround for Users

Until this is fixed, users attempting to use Ascend 910c with vLLM 0.20.2 should:
1. Use vLLM 0.24.0 + corresponding plugin version instead
2. Or wait for a corrected v0.2.0-rc0.post2 release

---

## Testing Artifacts

Complete installation manual with all discovered issues and fixes: [Ascend-910c-vLLM0.20.2-完整测试手册.md](attached)

---

## Labels

- `bug`
- `compatibility`
- `ascend`
- `vllm-0.20.2`

### PR DESCRIPTION
**Pull request by Al2O3Al2O3**
# Pull Request: Fix vLLM 0.20.2 compatibility issues in v0.2.0-rc0.post1

## Description

This PR fixes 3 critical API compatibility issues that prevent v0.2.0-rc0.post1 from working with vLLM 0.20.2 on Ascend 910c platform. These issues suggest the codebase was developed against a newer vLLM version and incorrectly tagged for 0.20.2.

### 1. Fix DeviceDetector import path for FlagGems 5.4.0-rc0 ✅

**File:** `vllm_fl/utils.py:8`

**Problem:** FlagGems 5.4.0-rc0 renamed `device.py` to `device_finder.py`, causing:
```python
ModuleNotFoundError: No module named 'flag_gems.runtime.backend.device'
```

**Fix:** Update import path to match FlagGems 5.4.0-rc0 structure.

---

### 2. Add conditional import for SharedFusedMoE ✅

**File:** `vllm_fl/dispatch/backends/vendor/ascend/impl/fused_moe/fused_moe.py:37`

**Problem:** vLLM 0.20.2 does not have `SharedFusedMoE` class (added in later versions), causing:
```python
ModuleNotFoundError: No module named 'vllm.model_executor.layers.fused_moe.shared_fused_moe'
```

**Fix:** 
- Wrap import in try-except, set to `None` if not available
- Update `AscendSharedFusedMoE` class to conditionally inherit from `SharedFusedMoE` only if available
- When `SharedFusedMoE` is `None`, class inherits only from `AscendFusedMoE` and still functions correctly

---

### 3. Remove multimodal_config parameter from MMEncoderAttention super().__init__() ✅

**File:** `vllm_fl/dispatch/backends/vendor/ascend/impl/mm_encoder_attention.py:58`

**Problem:** vLLM 0.20.2's `MMEncoderAttention.__init__()` only accepts 5 parameters, causing:
```python
TypeError: MMEncoderAttention.__init__() got an unexpected keyword argument 'multimodal_config'
```

**Fix:** Comment out `multimodal_config` parameter when calling `super().__init__()`. The parameter is still accepted by `AscendMMEncoderAttention.__init__()` for API compatibility, but not passed to the base class.

---

### 4. ASCEND_FL attention backend not registered ❌

**Error:** 
```python
ValueError: Unknown attention backend: 'ASCEND_FL'. Valid options are: FLASH_ATTN, ...
```

**Root Cause:** Plugin's `AscendFlashAttention` backend returns "ASCEND_FL" via `get_name()`, but this is never registered in vLLM 0.20.2's `AttentionBackendEnum`. vLLM 0.20.2 uses a strict enum-based registry that only accepts pre-registered backends.

**Why Not Fixed Here:** This requires architectural knowledge of where/how the plugin registers platform backends. The registration code should likely use:

```python
from vllm.v1.attention.backends.registry import register_backend, AttentionBackendEnum
register_backend(AttentionBackendEnum.CUSTOM, "vllm_fl.dispatch.backends.vendor.ascend.impl.attention.AscendFlashAttention")
```

**Request for Maintainers:** Please provide guidance on:
1. Where platform-specific backends should be registered for vLLM 0.20.2
2. Whether to use `AttentionBackendEnum.CUSTOM` or add a new enum member
3. How this differs from the approach used in newer vLLM versions

---

### Test Environment
- **Hardware:** Ascend 910c × 16 (64GB each)
- **CANN:** 9.0.0
- **OS:** openEuler 22.03 LTS-SP4 (ARM64)
- **Docker:** `quay.io/ascend/vllm-ascend:v0.20.2rc1-a3`

### Dependencies Tested
```bash
vLLM: 0.20.2 (empty install)
FlagGems: 5.4.0-rc0
FlagTree: 0.7.0-rc0-triton3.5
nanobind: 2.15.0 (requires >=2.4,<3.0)
cann-shmem: 1.6.0
```

### Test Results

**Before patch:**
- ❌ Import fails at `from flag_gems.runtime.backend.device import DeviceDetector`

**After fixing Issue 1:**
- ✅ Plugin imports successfully
- ❌ Serve crashes with `SharedFusedMoE` import error

**After fixing Issue 1+2:**
- ✅ Plugin loads
- ✅ Model architecture detection works
- ❌ Worker initialization fails with `multimodal_config` parameter error

**After fixing Issue 1+2+3:**
- ✅ All imports succeed
- ✅ Model initialization starts
- ✅ Vision transformer layers load
- ✅ MoE layers initialize
- ❌ Attention layer fails with "Unknown attention backend: ASCEND_FL"

**Note:** Full end-to-end serve test blocked by Issue 4 (backend registration).

---

## Verification Steps

To verify these fixes:

1. Apply patch to v0.2.0-rc0.post1
2. Install dependencies as specified above
3. Test import:
   ```python
   import torch, torch_npu
   import vllm_fl
   # Should succeed without errors
   ```

4. Test model loading (will fail at attention backend registration):
   ```bash
   export VLLM_PLUGINS=fl
   export VLLM_FL_PLATFORM=ascend
   export ASCEND_RT_VISIBLE_DEVICES=0,1
   
   python -c "
   from vllm import LLM
   llm = LLM(
       model='/models/Qwen3.6-35B-A3B',
       trust_remote_code=True,
       tensor_parallel_size=2,
       enforce_eager=True
   )
   "
   # Will reach attention backend initialization before failing
   ```

---

## Breaking Changes

None. All changes are backward-compatible:
- Conditional imports degrade gracefully when modules are missing
- Parameter removal only affects internal `super()` call
- Dynamic base class selection maintains functionality

---

## Related Issues

- See companion issue: "v0.2.0-rc0.post1 tag incompatible with vLLM 0.20.2 on Ascend 910c"

---

## Checklist

- [x] Code changes are minimal and focused
- [x] Each fix is independently tested
- [x] Changes maintain backward compatibility
- [x] Documentation updated (see related issue for detailed reproduction steps)
- [ ] Full end-to-end test (blocked by Issue 4)
- [ ] Maintainer guidance needed on attention backend registration

---

### For Maintainers

The root cause analysis suggests the v0.2.0-rc0.post1 tag may have been created from a branch that mixed vLLM 0.20.2 and 0.24.0+ code. Consider:

1. **Short term:** Apply this patch + fix Issue 4 → release as v0.2.0-rc0.post2
2. **Long term:** Implement vLLM version detection and conditional behavior
3. **Documentation:** Clarify which plugin versions support which vLLM versions

### For Users

A complete installation manual with all discovered issues and workarounds has been prepared: `Ascend-910c-vLLM0.20.2-完整测试手册.md` (available upon request)

---

## Acknowledgments

Testing performed on Ascend 910c hardware provided by BAAI. Issues discovered during FlagOS 2.2-RC0 integration testing.

### CODE REVIEW

**Comment by cyber-pioneer** [comment]
this pr is vllm0.20-related, should be pushed to branch release/0.2

**Comment by Al2O3Al2O3** [comment]
测试切错分支
